#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Plot analysis for SNAC layer ablation results.

Input CSV: generated by run_snac_layer_ablation.py, with columns:
  - file
  - wm
  - mask
  - mask_vec (json)
  - score

This script will:
  1) print a summary table (mean score per wm/mask)
  2) plot a heatmap: mask (row) x wm (col), value = mean score
  3) plot per-watermark bar chart of mask vs mean score
"""

import os
import argparse

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


def load_results(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    if "wm" not in df.columns or "mask" not in df.columns or "score" not in df.columns:
        raise ValueError("CSV must contain columns: wm, mask, score")
    return df


def order_masks(mask_names):
    """
    嘗試把 mask 以比較有意義的順序排序：

    - full_all
    - drop_last_k (k 由小到大)
    - keep_only_k (k 由小到大)
    - 其他字串照字母順序排在最後
    """
    full = [m for m in mask_names if m == "full_all"]
    drop = sorted(
        [m for m in mask_names if m.startswith("drop_last_")],
        key=lambda x: int(x.split("_")[-1])
    )
    keep = sorted(
        [m for m in mask_names if m.startswith("keep_only_")],
        key=lambda x: int(x.split("_")[-1])
    )
    others = sorted(set(mask_names) - set(full) - set(drop) - set(keep))
    return full + drop + keep + others


def plot_heatmap(df: pd.DataFrame, out_dir: str, title_suffix: str = ""):
    """
    mask (row) x wm (col) heatmap
    """
    grouped = df.groupby(["mask", "wm"])["score"].mean().reset_index()
    pivot = grouped.pivot(index="mask", columns="wm", values="score")

    # 排 mask 順序
    ordered_masks = order_masks(pivot.index.tolist())
    pivot = pivot.reindex(ordered_masks)

    plt.figure(figsize=(10, max(4, 0.4 * len(pivot.index))))
    im = plt.imshow(pivot.values, aspect="auto", interpolation="nearest")
    plt.colorbar(im, label="mean score")

    plt.xticks(
        np.arange(len(pivot.columns)),
        pivot.columns,
        rotation=45,
        ha="right"
    )
    plt.yticks(
        np.arange(len(pivot.index)),
        pivot.index
    )

    plt.title(f"SNAC Layer Ablation Heatmap{title_suffix}")
    plt.tight_layout()

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "snac_layer_ablation_heatmap.png")
    plt.savefig(out_path)
    plt.close()
    print(f"[PLOT] heatmap saved to {out_path}")


def plot_per_wm_bars(df: pd.DataFrame, out_dir: str):
    """
    對每個 watermark 畫一張 bar chart:
      x: mask (有排序)
      y: mean score
    """
    os.makedirs(out_dir, exist_ok=True)
    grouped = df.groupby(["wm", "mask"])["score"].mean().reset_index()

    for wm_name, sub in grouped.groupby("wm"):
        masks = order_masks(sub["mask"].tolist())
        sub = sub.set_index("mask").reindex(masks).reset_index()

        plt.figure(figsize=(10, 4))
        plt.bar(sub["mask"], sub["score"])
        plt.xticks(rotation=45, ha="right")
        plt.ylabel("mean score")
        plt.title(f"SNAC Layer Ablation - {wm_name}")
        plt.tight_layout()

        out_path = os.path.join(out_dir, f"snac_layer_ablation_{wm_name}.png")
        plt.savefig(out_path)
        plt.close()
        print(f"[PLOT] bar chart saved to {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Plot SNAC layer ablation results (per watermark / per mask)."
    )
    parser.add_argument(
        "--csv",
        type=str,
        required=True,
        help="Path to snac_layer_ablation_*.csv"
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default=None,
        help="Directory to save plots (default: same dir as CSV + '/snac_layer_ablation_plots')"
    )
    args = parser.parse_args()

    csv_abs = os.path.abspath(args.csv)
    df = load_results(csv_abs)

    if args.out_dir is None:
        base_dir = os.path.dirname(csv_abs)
        out_dir = os.path.join(base_dir, "snac_layer_ablation_plots")
    else:
        out_dir = os.path.abspath(args.out_dir)

    os.makedirs(out_dir, exist_ok=True)

    print("[INFO] CSV loaded from:", csv_abs)
    print("[INFO] rows:", len(df))
    print("[INFO] watermarks:", df["wm"].unique())
    print("[INFO] masks:", sorted(df["mask"].unique()))

    # 小 summary
    print("\n[SUMMARY] mean score by wm/mask:")
    print(df.groupby(["wm", "mask"])["score"].mean())

    # 畫 heatmap
    plot_heatmap(df, out_dir)

    # 每個 WM 畫一張 bar chart
    plot_per_wm_bars(df, out_dir)


if __name__ == "__main__":
    main()
